import type { ActorProfile, BlogPost, CastingCall } from '@/types';

export const FEATURED_ACTORS: ActorProfile[] = [
  {
    id: 'fa1',
    name: 'Vijay Kumar',
    email: 'vijay@example.com',
    role: 'actor',
    age: 26,
    location: 'Hyderabad',
    skills: ['Acting', 'Dancing', 'Horse Riding'],
    height: "5'11\"",
    languages: ['Telugu', 'English', 'Hindi'],
    profilePhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200',
  },
  {
    id: 'fa2',
    name: 'Ananya Rao',
    email: 'ananya@example.com',
    role: 'actor',
    age: 24,
    location: 'Hyderabad',
    skills: ['Acting', 'Classical Dance', 'Singing'],
    height: "5'6\"",
    languages: ['Telugu', 'Tamil', 'English'],
    profilePhoto: 'https://images.unsplash.com/photo-1621184414184-0155f0ce800a?auto=format&fit=crop&q=80&w=200',
  },
  {
    id: 'fa3',
    name: 'Siddharth S.',
    email: 'sid@example.com',
    role: 'actor',
    age: 28,
    location: 'Secunderabad',
    skills: ['Action', 'Martial Arts', 'Acting'],
    height: "6'1\"",
    languages: ['Telugu', 'Hindi', 'English'],
    profilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
  },
  {
    id: 'fa4',
    name: 'Priya Mani',
    email: 'priya@example.com',
    role: 'actor',
    age: 23,
    location: 'Hyderabad',
    skills: ['Acting', 'Modern Dance'],
    height: "5'5\"",
    languages: ['Telugu', 'Kannada', 'English'],
    profilePhoto: 'https://images.unsplash.com/photo-1614283233556-f35b0c801ef1?auto=format&fit=crop&q=80&w=200',
  },
  {
    id: 'fa5',
    name: 'Karthik Aryan',
    email: 'karthik@example.com',
    role: 'actor',
    age: 27,
    location: 'Hyderabad',
    skills: ['Comedy', 'Acting', 'Dancing'],
    height: "5'10\"",
    languages: ['Telugu', 'English'],
    profilePhoto: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'SS Rajamouli Announces Next Mega Project with Mahesh Babu',
    excerpt: 'The visionary director is set to redefine Indian cinema once again with an action-adventure globe-trotting epic.',
    date: '2026-05-01',
    author: 'Cinema Desk',
    imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=400',
    category: 'Industry News',
  },
  {
    id: 'b2',
    title: 'Upcoming OTT Releases to Watch Out for this Summer',
    excerpt: 'From intense thrillers to light-hearted rom-coms, here is your definitive guide to Telugu OTT content this month.',
    date: '2026-04-28',
    author: 'Film Hub',
    imageUrl: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?auto=format&fit=crop&q=80&w=400',
    category: 'Watchlist',
  },
  {
    id: 'b3',
    title: 'Behind the Scenes: The Magic of VFX in Modern Telugu Films',
    excerpt: 'Exclusive interview with top VFX supervisors on how they created the breathtaking visuals for the latest blockbusters.',
    date: '2026-04-25',
    author: 'Tech Talk',
    imageUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&q=80&w=400',
    category: 'Behind the Scenes',
  },
];

export const SEED_CASTING_CALLS: CastingCall[] = [
  {
    id: '1',
    recruiterId: 'r1',
    title: 'Lead Actor for Web Series',
    description: 'Looking for a dynamic male lead for an upcoming Telugu thriller web series.',
    roleDescription: 'Protagonist, intense character, age 25-30.',
    ageRange: '22-32',
    location: 'Hyderabad',
    budget: '₹50,000 - ₹1,00,000',
    deadline: '2026-06-01',
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: '2',
    recruiterId: 'r1',
    title: 'Supporting Actress (Mother Role)',
    description: 'Emotional character role for a feature film.',
    roleDescription: 'Kind-hearted mother of the lead character.',
    ageRange: '40-55',
    location: 'Hyderabad',
    budget: '₹30,000 per day',
    deadline: '2026-05-20',
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: '3',
    recruiterId: 'r2',
    title: 'Background Dancers - Modern Folk',
    description: 'Energetic group needed for a big-budget song sequence.',
    roleDescription: 'Proficient in Telugu folk and contemporary dance.',
    ageRange: '18-25',
    location: 'Hyderabad',
    budget: 'Competitive',
    deadline: '2026-05-15',
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: '4',
    recruiterId: 'r2',
    title: 'Twin Sisters for Commercial',
    description: 'National detergent brand advertisement. Looking for identical twins.',
    roleDescription: 'Charming, expressive, age 6-10.',
    ageRange: '6-10',
    location: 'Hyderabad',
    budget: '₹25,000 each',
    deadline: '2026-05-25',
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: '5',
    recruiterId: 'r3',
    title: 'Action Stunt Doubles',
    description: 'High-octane action sequence for a pan-India project.',
    roleDescription: 'Expertise in wirework and bike stunts required.',
    ageRange: '20-40',
    location: 'Ramoji Film City',
    budget: 'Daily basis - High',
    deadline: '2026-05-12',
    createdAt: '2026-04-01T00:00:00Z',
  },
];
